### PR TITLE
Add a page to collect soft signals

### PR DESCRIPTION
**Pull request by JeremyRubin**
*Bip-119 allows you to have "precomitted transactions" when you create an address. This let's you build many kinds of wonderful smart contracts for use cases like rate-limited vaults for custody, sidechain fund management, congestion control queues, etc using tools like [sapio](learn.sapio-lang.org)*

This is a draft of a page to collect soft signals from various entities in the space for BIP-119 CheckTemplateVerify.

Before merge, should gather a couple more entities that would like to be represented here.

to review the BIP

- Spec: https://github.com/bitcoin/bips/blob/master/bip-0119.mediawiki
- PR: https://github.com/bitcoin/bitcoin/pull/21702

### CODE REVIEW

**Comment by bensig** [comment]
Is this the best page to see BIP-119?
[https://github.com/bitcoin/bips/blob/master/bip-0119.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0119.mediawiki)

**Comment by JeremyRubin** [comment]
@bensig that is the formal specification and most up to date draft, correct.

**Comment by JeremyRubin** [comment]
also relevant is https://github.com/bitcoin/bitcoin/pull/21702 which has the PR implementing it

**Comment by esneider** [comment]
Could you add Muun to the list?

**Comment by matthiasdebernardini** [comment]
Add my name to the list, you can link this tweet https://twitter.com/matthiasdebern/status/1436007746772557827?s=20

**Pull request merged**
