### PR TITLE
Update devs.yaml

### PR DESCRIPTION
**Pull request by reardencode**

### CODE REVIEW

**Comment by JeremyRubin** [comment]
thanks for adding your own link, thoughtful!

**Comment by JeremyRubin** [comment]
it helps a lot (for your nack to be 'counted' by others) if you give a more concrete justification for why you don't like the proposal.

**Comment by reardencode** [comment]
1. After working on Taproot support, I've realized how important having the surrounding pieces ready before the soft fork is locked in is. I think the closest analogue with the Taproot soft fork is MuSig2, which didn't even have a reference implementation at the time of activation (let alone lock-in). What if some incompatibility had been found between BIP-340 signature verification and MuSig2 signing? I'd like to see demonstrations with running code on OP_CTV, specifically showing that a plurality of covenant use-cases are covered.
2. I'm not yet convinced that OP_CTV is the singular best way to bring forward covenants to Bitcoin. I haven't fully reviewed alternative proposals, but I would be interested to see an option for a key path covenant.

I think the opportunity for covenants in Bitcoin is huge (eg. your Sapio work) but I also want to make sure that we get it right.

**Comment by JeremyRubin** [comment]
Gotcha! have you seen rubin.io/advent21 and learn.sapio-lang.org? There are lots of exaples.

What's the threshold you're looking for of "running code" that compiling and using the examples in sapio isn't meeting?

Can you define what you mean by key-path covenant btw?

I agree getting it right is very important indeed :)

**Comment by reardencode** [comment]
I did read through most of your 2021 advent calendar. If I understand correctly there is currently an emulator of OP_CTV, but no running implementation that is consensus compatible. I have concerns about the practicality of the compiled contracts from a usability and fees perspective, which makes me wonder if there's a way to move more of the covenant checking and contract steps off-chain, but validate on chain, and if that would not end up looking like OP_CTV, but perhaps OP_HOWDIDYOUGETHERE.

Similarly, I wonder if it would be possible to (either as a new segwit version, or otherwise) define a key path spend that must be tweaked by the spending TX's hash - eg. sig checking for segwit vX would require hashing the TX, lifting it onto the curve, subtracting that point from the published pubkey, and then checking the signature. This would dramatically reduce the on chain weight of spending contract inputs that have a common spend path involving CTV. Potentially, such a construction could also include a taproot tweak under the CTV tweak with the vX control block revealing the CTV hash and whether it needs to be matched or not.

Obviously none of this is fully fleshed out, but these thoughts are why I am not ready to support OP_CTV soft fork yet.

**Question for you:** I saw a brief mention in BIP119 of OP_CTV flags to control what parts of the spending transaction are hashed. Have you run into any contracts you want to write, but are either prevented from writing or have to go through additional steps to write because of the lack of such constraint reducing flags?

**Comment by JeremyRubin** [comment]
> I did read through most of your 2021 advent calendar. If I understand correctly there is currently an emulator of OP_CTV, but no running implementation that is consensus compatible.

Nope, the emulator works today! E.g., I used it for my hanukkah project  https://twitter.com/JeremyRubin/status/1465076638748577794

> I have concerns about the practicality of the compiled contracts from a usability and fees perspective, which makes me wonder if there's a way to move more of the covenant checking and contract steps off-chain, but validate on chain, and if that would not end up looking like OP_CTV, but perhaps OP_HOWDIDYOUGETHERE.

Yeah that is pretty much what CTV is. See bram cohen's description of it https://twitter.com/bramcohen/status/1224823869933899776

> Similarly, I wonder if it would be possible to (either as a new segwit version, or otherwise) define a key path spend that must be tweaked by the spending TX's hash - eg. sig checking for segwit vX would require hashing the TX, lifting it onto the curve, subtracting that point from the published pubkey, and then checking the signature. This would dramatically reduce the on chain weight of spending contract inputs that have a common spend path involving CTV. Potentially, such a construction could also include a taproot tweak under the CTV tweak with the vX control block revealing the CTV hash if it doesn't need to be matched.

ah... i proposed this > 2 years ago, but the pushback was 'no more changes to taproot' at the time. I can dig up some links if curious... but now such an approach cannot be done without a new witness version. when new witness version comes up, we can consider including that sort of thing if it's popular.


> Obviously none of this is fully fleshed out, but these thoughts are why I am not ready to support OP_CTV soft fork yet.

it really does seem like you're thinking through great questions and are on an excellent path to either like CTV or at least learn a lot more!

> Question for you: I saw a brief mention in BIP119 of OP_CTV flags to control what parts of the spending transaction are hashed. Have you run into any contracts you want to write, but are either prevented from writing or have to go through additional steps to write because of the lack of such constraint reducing flags?

Hmmmm. Sort of. There's a particular "zen" of CTV you have to follow, which I think people don't like. It's sort of as follows:

1. Decide on a high level goal
2. figure out how to implement something with CTV/Sapio
3. See if the low-level implementation is good for the high level goal

usually, with CTV I am able to make something that is pretty good.

What can happen for folks is:

1. Decide on a very specific goal
2. Figure out the ideal implementation of that goal
3. See if CTV can do it

That path is obviously going to upset you!

For example, Payment Pools work really nicely in CTV, and they operate under the assumption that partitioning during liveness faults is OK. E.g., if it is dead, split in half. But if you try to come up with Payment Pools as a specific API, you might say "Anyone SHould be able to Exit in Any Order". That's _over_ constrained.

And when you do out the math on designs with anyone can exit in any order v.s. CTV's just split the pool design, it turns out those any-order designs are a lot more expensive.

**Comment by JeremyRubin** [comment]
presesed enter a little early:

that's all to say that there are definitely things that are to be desired for more flexibility. but usually when you trace out the full picture the CTV version is decent enough.

**Comment by reardencode** [comment]
Thanks! I'll keep learning and change my answer here as necessary.

**Comment by reardencode** [comment]
I'm getting more convinced of OP_CTV after reading the Entroot proposal. With Entroot (or similar) a forward covenant could be used on a key path spend with just ~35 bytes of additional witness data.

 > > I did read through most of your 2021 advent calendar. If I understand correctly there is currently an emulator of OP_CTV, but no running implementation that is consensus compatible.

> Nope, the emulator works today! E.g., I used it for my hanukkah project https://twitter.com/JeremyRubin/status/1465076638748577794

I knew about the emulator (essentially an oracle), but is there a running implementation of OP_CTV on a full bitcoin node that also works with Sapio?

**Comment by JeremyRubin** [comment]
Yep! I think (AFAIU Entroot) that should work perfectly. Cool idea!

Ah. What do you mean? https://github.com/bitcoin/bitcoin/pull/21702 exists. You can boot this up and run a regtest or signet node with it enabled.

**Pull request merged**
